/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package topsusicm;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/**
 *
 * @author BagusThanatos (github.com/BagusThanatos)
 */
public class PanelTest extends javax.swing.JPanel {

    /**
     * Creates new form PanelTest
     */
    private TopsusICM m;
    Database d;
    public PanelTest() {
        initComponents();
    }
    public PanelTest(TopsusICM m,Database d){
        initComponents();
        this.m=m;
        this.d =d ;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        textSoal = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textA = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        textB = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        textC = new javax.swing.JTextArea();
        radButA = new javax.swing.JRadioButton();
        radButB = new javax.swing.JRadioButton();
        radButC = new javax.swing.JRadioButton();
        butNext = new javax.swing.JButton();
        butCancel = new javax.swing.JButton();
        butBack = new javax.swing.JButton();
        labelTest = new javax.swing.JLabel();

        textSoal.setColumns(20);
        textSoal.setRows(5);
        jScrollPane1.setViewportView(textSoal);

        textA.setColumns(20);
        textA.setLineWrap(true);
        textA.setRows(5);
        jScrollPane2.setViewportView(textA);

        textB.setColumns(20);
        textB.setLineWrap(true);
        textB.setRows(5);
        jScrollPane3.setViewportView(textB);

        textC.setColumns(20);
        textC.setLineWrap(true);
        textC.setRows(5);
        jScrollPane4.setViewportView(textC);

        buttonGroup1.add(radButA);
        radButA.setText("A");

        buttonGroup1.add(radButB);
        radButB.setText("B");

        buttonGroup1.add(radButC);
        radButC.setText("C");

        butNext.setText("Next");
        butNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butNextActionPerformed(evt);
            }
        });

        butCancel.setText("Cancel");
        butCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancelActionPerformed(evt);
            }
        });

        butBack.setText("Back");
        butBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBackActionPerformed(evt);
            }
        });

        labelTest.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTest.setText("TEST: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(radButA)
                        .addGap(152, 152, 152)
                        .addComponent(radButB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radButC)
                        .addGap(69, 69, 69))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(butCancel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(butBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(butNext))
                            .addComponent(jScrollPane4))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(labelTest)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(labelTest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radButA)
                    .addComponent(radButB)
                    .addComponent(radButC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butNext)
                    .addComponent(butCancel)
                    .addComponent(butBack))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void butCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancelActionPerformed
        m.changePanel(TopsusICM.PANELMATERI);
    }//GEN-LAST:event_butCancelActionPerformed

    private void butBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBackActionPerformed
        if(m.no>1) {
            m.no--;
            updateSoal();
            setJawaban(m.answer[m.no-1]);
        }
    }//GEN-LAST:event_butBackActionPerformed

    private void butNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butNextActionPerformed
        if(m.no<m.maksno) {
            int answer = getAnswer();
            if (answer==0) {
                JOptionPane.showMessageDialog(m, "Mohon pilih satu jawaban");
                return;
            }
            m.answer[m.no-1]=answer;
            m.no++;
            updateSoal();
            setJawaban(m.answer[m.no-1]);
        }
        else {
            m.answer[m.no-1]=getAnswer();
            int val=JOptionPane.showConfirmDialog(m, "Apakah anda ingin Submit?");
            if(val == JOptionPane.OK_OPTION){
                String q;
                if (m.maksno==5){
                    double nilai[] = new double[5];
                    for(int i=1;i<=5;i++) {
                        try {
                            String q1 = "select * from pretest where nomorpretest="+i;
                            ResultSet rs1 = d.getData(q1);
                            rs1.next();
                            switch(m.answer[i-1]){
                                case 1:
                                    nilai[i-1]= rs1.getDouble("npjwbA");
                                    break;
                                case 2:
                                    nilai[i-1]= rs1.getDouble("npjwbB");
                                    break;
                                case 3:
                                    nilai[i-1]= rs1.getDouble("npjwbC");
                                    break;
                            }
                        } catch (SQLException ex) {
                            Logger.getLogger(PanelTest.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    int gol;
                    if(nilai[0]>=0.7) {
                        if(nilai[1]>=0.7) {
                            if(nilai[2]>=0.7) {
                                if(nilai[3]>=0.7) {
                                   if(nilai[4]>=0.7) {
                                       gol=5;
                                   } else gol =4;
                                } else gol =3;
                            }else gol =2;
                        } else gol =1;
                    } else {
                        gol =0;
                    }
                    System.out.println(m.username);
                    d.query("update akun set golongan="+gol+" where username='"+m.username+"'");
                    q = "insert into nilaipretest "
                            + " (`id_nilaipretest`, `nilaip1`, "
                            + "`nilaip2`, `nilaip3`, `nilaip4`, `nilaip5`, `username`) "
                            + "values(NULL,"+nilai[0]+","+nilai[1]
                            +","+nilai[2]+","+nilai[3]+","+nilai[4]+",'"+m.username+"')";
                }else{
                    double nilai[] = new double[2];
                    for(int i=1;i<=2;i++) {
                        try {
                            String q1 = "select * from soal where nomorsoal="+i+" and id_materi='"+m.idmateri+"'";
                            ResultSet rs1 = d.getData(q1);
                            rs1.next();
                            switch(m.answer[i-1]){
                                case 1:
                                    nilai[i-1]= rs1.getDouble("n_jwb_A");
                                    break;
                                case 2:
                                    nilai[i-1]= rs1.getDouble("n_jwb_B");
                                    break;
                                case 3:
                                    nilai[i-1]= rs1.getDouble("n_jwb_C");
                                    break;
                            }
                        } catch (SQLException ex) {
                            Logger.getLogger(PanelTest.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    String status;
                    double total = nilai[0]+nilai[1];
                    if (total >=0.9) status ="adv";
                    else if(total >=0.4) status ="int";
                    else status = "beg";
                    q = "insert into nilai values(NULL,"+nilai[0]+","+nilai[1]+
                            ",'"+status+"','"+m.username+"','"+m.idmateri+"')";
                }
                m.changePanel(TopsusICM.PANELMATERI);
                d.query(q);
            }
        }
    }//GEN-LAST:event_butNextActionPerformed

    public void setTitle(String s){
        labelTest.setText(s);
    }
    private int getAnswer(){
        if(radButA.isSelected()) return 1;
        if(radButB.isSelected()) return 2;
        if(radButC.isSelected()) return 3;
        return 0;
    }
    private void setJawaban(int j){
        switch(j){
            case 1 : 
                buttonGroup1.setSelected(radButA.getModel(), true);
                break;
            case 2:
                buttonGroup1.setSelected(radButB.getModel(), true);
                break;
            case 3:
                buttonGroup1.setSelected(radButC.getModel(), true);
                break;
            default:;
        }
           
    }
    void updateSoal(){
        try {
            String query,isi,jwb;
            if (m.maksno==5){
                isi="isipretest";
                jwb="pjwb";
                query = "select * from pretest where nomorpretest="+m.no;
            } else {
                isi="isisoal";
                jwb="jawaban_";
                query = "select * from soal where id_materi='"+m.idmateri+"'"+
                        "and nomorsoal="+m.no;
            }
            ResultSet rs = d.getData(query);
            rs.next();
            textSoal.setText(rs.getString(isi));
            textA.setText(rs.getString(jwb+"A"));
            textB.setText(rs.getString(jwb+"B"));
            textC.setText(rs.getString(jwb+"C"));
        } catch (SQLException ex) {
            Logger.getLogger(PanelTest.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butBack;
    private javax.swing.JButton butCancel;
    private javax.swing.JButton butNext;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelTest;
    private javax.swing.JRadioButton radButA;
    private javax.swing.JRadioButton radButB;
    private javax.swing.JRadioButton radButC;
    private javax.swing.JTextArea textA;
    private javax.swing.JTextArea textB;
    private javax.swing.JTextArea textC;
    private javax.swing.JTextArea textSoal;
    // End of variables declaration//GEN-END:variables
}
